module.exports = {
	processors: ['stylelint-processor-html'],
	extends: ['stylelint-config-recommended'],
	rules: {
		indentation: 'tab',
		'string-quotes': 'single',
		'no-duplicate-selectors': true,
		'color-hex-case': 'upper',
		'color-named': 'never',
		'selector-no-qualifying-type': true,
		'selector-combinator-space-after': 'always',
		'selector-attribute-quotes': 'always',
		'selector-attribute-operator-space-before': 'always',
		'selector-attribute-operator-space-after': 'always',
		'selector-attribute-brackets-space-inside': 'never',
		'declaration-colon-space-before': 'never',
		'declaration-colon-space-after': 'always',
		'number-leading-zero': 'always',
		'function-url-quotes': 'always',
		'font-weight-notation': 'numeric',
		'comment-empty-line-before': 'always',
		'rule-empty-line-before': 'always-multi-line',
		'selector-pseudo-class-parentheses-space-inside': 'never',
		'media-feature-range-operator-space-before': 'always',
		'media-feature-range-operator-space-after': 'always',
		'media-feature-parentheses-space-inside': 'never',
		'media-feature-colon-space-before': 'never',
		'media-feature-colon-space-after': 'always',
	},
};
